# This file is not necessary if you don't use azure pipl to deploy your chart
pr: none
trigger:
  branches:
    include:
    - master
    - resize-sts-operator
  paths:
    include:
    - resize-statefulset-operator/auto-resize-operator/auto-resize/Chart.yaml
resources:
  repositories:
  - repository: # HELM REPO NAME #
    type: git
    name: # INPUT YOUR NAME#
    ref: stable
stages:
- stage: build
  jobs:
  - template: # YOUR TEMPLATE #
    parameters:
      job: build_auto_resize_operator
      chartPath: resize-statefulset-operator/auto-resize-operator/auto-resize
      variableGroup: # ENTER YOUR GROUP #
      autoVersioning: false
