# Build image
# This file is not necessary if you don't use azure pipl to build image
pr: none
trigger:
  branches:
    include:
    - master
resources:
  repositories:
  - repository: # INPUT YOUR REPO #
    type: git
    name: # INPUT YOUR NAME #
    ref: stable
stages:
- stage: build_image
  jobs:
  - template: # INPUR YOUR TEMPLATE #
    parameters:
      job: build_image_resize_sts_operator
      imageName: resize_sts_operator
      dockerfilePath: operator-python/Dockerfile
      buildContextPath: operator-python/
