# This file is not necessary if you don't use azure pipl to deploy your chart
pr: none
trigger:
  branches:
    include:
    - master
    - resize-sts-operator
  paths:
    include:
    - resize-statefulset-operator/webhook/rso-webhook-server/Chart.yaml
resources:
  repositories:
  - repository: # INPUT REPO #
    type: git
    name: ".../...build"
    ref: stable
stages:
- stage: build
  jobs:
  - template: helm-build-job.yml@templates
    parameters:
      job: build_webhook_server
      chartPath: k8s/helm/resize-statefulset-operator/webhook/rso-webhook-server
      variableGroup: # INPUT GROUP #
      autoVersioning: false
