apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "rso-webhook-server.fullname" . }}
webhooks:
- name: {{ .Values.mutatingwebhookconfiguration.name }}
  sideEffects: None
  admissionReviewVersions: ["v1", "v1beta1"]
  # namespaceSelector:
  #   matchExpressions:
  #   - key: kubernetes.io/metadata.name
  #     operator: In
  #     values: ["intern-dev"]
  rules:
  - operations: ["UPDATE"]
    apiGroups: ["apps"]
    apiVersions: ["v1"]
    resources: ["statefulsets"]
  clientConfig:
    service:
      name: webhook
      namespace: {{ .Release.Namespace }}
      path: "/mutating"
      port: 443
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lVTi9DQXd0Wkg1eWhiU0NYVlNVUjYwc1pjK29Bd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0lqRWdNQjRHQTFVRUF3d1hiWFYwWVhScGJtY3RkMlZpYUc5dmF5NXljMjh1YVc4d0lCY05Nak13TlRBMApNRGMwTnpRd1doZ1BNakExTURBNU1Ua3dOelEzTkRCYU1DSXhJREFlQmdOVkJBTU1GMjExZEdGMGFXNW5MWGRsClltaHZiMnN1Y25OdkxtbHZNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXhkTFQKTVhmN1g5VFUvUVRCOUY0SEVGQmhJcW1HSllaV1FBdUV5aDJPWGVnUk1GSW1SRnJOZ2xLdDNCYktQdERhUTFnMwpaNjIvek85cGhMazM3UXJUc1JQQW1KTUd4a1pWU0YxNDBjcHdUWTFOOHpSSGtUMEtLRTdDMzJXZFE5aU5zNVlxCkQ3b2pzSXZ0ejFTbXJiZ1hhc2JnU09VSmt0bEcxSEdPSzQrM1RmbFR0bzRadEdONUhCV0toSDVmRTc5QlVJL1QKdXh1a2wrd1FWTkYyQjhHQ3N4NHBQeFMrUXQ0RE03Ti9LbDRKRG1Td2dpQ2ttekpySmc1ak9TbmF0eVJ3cC9qOApXM3NtYjJIVUFzRjJqbkcra0c3NWpGS0xTS005bVpuTEJLUzlubUx6bFhSNXRjSkVUTWU3RGUycWxFVFI3ZVRZClFZTlE4bWFRdU0xZG0yNWpRd0lEQVFBQm8xTXdVVEFkQmdOVkhRNEVGZ1FVaVN5KzYvOEttRWttdUZWTDhIbkoKYWZaakJxQXdId1lEVlIwakJCZ3dGb0FVaVN5KzYvOEttRWttdUZWTDhIbkphZlpqQnFBd0R3WURWUjBUQVFILwpCQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFIMnVTdXBmaVVobTJqb0xTNmcrN1Q2WTRxM25QCkFmMERUMlJVR0xwcjJyVVl4L25TTmw0T1FjWVlGczBTeDhocGVwT0o5TDRJbUVoTTdzb0JITWI4UTdzbm1IVGMKaldxWTcrVzRyYW1UUTBudFVleTlnMHEvZmtYWXlnRXJpcGFwd0tvekwycko5eTU3ZU1UdkRZVVA0d2xPWEpEcwpFUnB6STI3eCtNMG1rN0JhdkJZWDlmZ2l4dUNxeDkyOFpJak1wLytIU2VVbE1yTHAwS1R0VjBlZldXSmU2V1NaClQrdDEwOGpZK21YRVptUWpiejRPYkhrTk4wNjN3TGdxVDBSZ1hST0RRN0VXNDRNQnBsRHBhNjBmR3RjemNUQysKVXBEWW9pYVhLTDhWVXVETWdtS3hRdjlrQzhKU1B4U3ZveGR3SHZXZU9sZDFVUHRzeXdQdXhJY3Fjdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K