# This file is not necessary if you don't use azure pipl to deploy your chart
pr: none
trigger:
  branches:
    include:
    - master
    - operator-python
  paths:
    include:
    - operator-python/chart/Chart.yaml
resources:
  repositories:
  - repository: # YOUR HELM REPO #
    type: git
    name: # BUILD CHART #
    ref: stable
stages:
- stage: build
  jobs:
  - template: helm-build-job.yml@templates
    parameters:
      job: build_resize_sts_operator
      chartPath: operator-python/chart
      variableGroup: # GROUP #
      autoVersioning: false
