apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: { { include "resize-statefulset-operator.fullname" . } }
  labels: { { - include "resize-statefulset-operator.labels" . | nindent 4 } }
rules:
  - resources: ["statefulsets"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
    apiGroups: ["apps"]
  - resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update"]
    apiGroups: ["*"]
  - resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
    apiGroups: ["*"]
  - resources: ["namespaces"]
    verbs: ["get", "list"]
    apiGroups: ["*"]
  - resources: ["pods", "pods/log"]
    verbs: ["get", "list"]
    apiGroups: [""]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
